data: config/datasets/mvimage_bmp.yml
exp: config/mvmp/detect_match_triangulate.yml #_fitSMPL.yml
data_opts:
  root: TO_BE_FILLED
  subs: []
  subs_vis: ['D8_C_12M_022502460067', 'D9_C_12M_022502060012', 'D9_C_12M_022502460075', 'D9_C_12M_022502460080'] #['D7_C_12M_022502260003']
  ranges: [50, 100, 1]
exp_opts:
  output: output/yoom3
  at_step:
    detect:
      args:
        min_length: 300
        max_length: 2500
    match:
      args:
        cfg_match:
          distance:
            threshold_track: 0.05
          triangulate:
            min_view: 3 # at least 3 views to triangulate
            min_view_body: 3 # at least 5 views to triangulate
            dist_max: 100 # pixel
            dist_track: 100 # 100mm；
        cfg_track:
          max_person: 6
          final_ranges: [[-3, -3, 0.], [3, 3, 3.]] # 最终的输出的range，仅用于输出的时候的筛选
          final_max_person: 3
  at_final:
    collect:
      args:
        min_frame: 100
    fitting_each_person:
      args:
        stages:
          refine_poses:
            args:
              loss:
                smooth:
                  weight: 5.
    vis_render:
      args:
        view_list: [2]
        scale: 1.